CREATE OR REPLACE TYPE tp_fones AS OBJECT(
    numero VARCHAR2(14)
)FINAL;
/

CREATE OR REPLACE TYPE VA_FONES AS VARRAY(4) OF tp_fones;
/

CREATE OR REPLACE TYPE tp_pessoa AS OBJECT(
	Cpf INT,
	Nome VARCHAR2(30),
	Email  VARCHAR2(30),
	lista_telefones VA_FONES
)NOT FINAL NOT INSTANTIABLE;
/
